server {
    listen 4000;
    root /usr/share/nginx/html;
    index index.html;
    # Servir arquivos estáticos diretamente (sem fallback SPA)
    location / {
        try_files $uri $uri/ =404;
    }
}
